version: '3.7'
services:
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: es02
    mem_limit: 512m
    environment:
    # Network settings
      - network.publish_host=172.31.14.56 # ES02's ec2 private IP
      - transport.publish_host=172.31.14.56 # ES02's ec2 private IP
    # Node settings
      - node.name=es02
      - cluster.name=cv-cluster
      - discovery.seed_hosts=172.31.14.196:9300 # ES01's ec2 private IP
      - cluster.initial_master_nodes=172.31.14.196:9300 # ES01's ec2 private IP
      - bootstrap.memory_lock=false
      - ES_JAVA_OPTS=-Xms128m -Xmx128m -XX:+UseG1GC # Heap size for Elasticsearch + Garbage Collector
      - xpack.ml.enabled=false
    # Security settings
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - http.cors.allow-methods=OPTIONS,GET,POST
      - http.cors.allow-headers=Content-Type, x-elastic-client-meta
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    ports:
      - '9201:9200'
      - '9300:9300' # For communciation in deployment

volumes:
  esdata02: