version: '3.7'
services:
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: es02
    mem_limit: 512m
    environment:
      - network.publish_host=172.31.14.56
      - transport.publish_host=172.31.14.56
      - node.name=es02
      - cluster.name=cv-cluster
      - discovery.seed_hosts=172.31.14.196:9300,172.31.14.56:9300
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=false
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.authc.api_key.enabled=true
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=/usr/share/elasticsearch/config/certs/es02/es02.key
      - xpack.security.transport.ssl.certificate=/usr/share/elasticsearch/config/certs/es02/es02.crt
      - xpack.security.transport.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=basic
      - ES_JAVA_OPTS=-Xms128m -Xmx128m -XX:+UseG1GC
      - xpack.ml.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - http.cors.allow-methods=OPTIONS,GET,POST
      - http.cors.allow-headers=Authorization,Content-Type,x-elastic-client-meta
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
      - ../certs:/usr/share/elasticsearch/config/certs
    ports:
      - '9201:9200'
      - '9300:9300' # for deployment, comment out for local
    # networks: # needed for local
    #   - esnet

volumes:
  esdata02:

# networks: # needed for local
#   esnet:
#     external: true
