version: '3.7'
services:
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: es02
    mem_limit: 512m
    environment:
      - node.name=es02
      - cluster.name=cv-cluster
      - discovery.seed_hosts=172.31.14.196:9300
      - bootstrap.memory_lock=false
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms128m -Xmx128m
      - xpack.ml.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - http.cors.allow-methods=OPTIONS,GET,POST
      - http.cors.allow-headers=Content-Type, x-elastic-client-meta
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    ports:
      - '9201:9200'
      - '9300:9300' # for deployment, comment out for local
    # networks: # needed for local
    #   - esnet

volumes:
  esdata02:

# networks: # needed for local
#   esnet:
#     external: true
