version: '3.7'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: es01
    mem_limit: 512m
    environment:
      # - network.host=0.0.0.0
      - node.name=es01
      - cluster.name=cv-cluster
      - discovery.seed_hosts=es01,172.31.14.56:9300
      # - cluster.initial_master_nodes=172.31.14.196:9300,172.31.14.56:9300
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=false
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms128m -Xmx128m -XX:+UseG1GC
      - xpack.ml.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - http.cors.allow-methods=OPTIONS,GET,POST
      - http.cors.allow-headers=Content-Type, x-elastic-client-meta
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
      - '9300:9300' # for deployment, comment for local
    # networks: # needed for local
    #   - esnet

volumes:
  esdata01:

# networks: # needed for local
#   esnet:
#     external: true
